spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rabbit?useUnicode=true&characterEncoding=UTF8
    username: 'root'
    password: 'root'
  application:
    name: spring-boot-rabbitmq-normal-trade
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    userName: guest
    passWord: guest
    virtualHost: /
    #   在消息没有被路由到合适队列情况下会将消息返还给消息发布者
    #   当mandatory标志位设置为true时，如果exchange根据自身类型和消息routingKey无法找到一个合适的queue存储消息，
    #    那么broker会调用basic.return方法将消息返还给生产者;当mandatory设置为false时，
    #    出现上述情况broker会直接将消息丢弃;通俗的讲，mandatory标志告诉broker代理服务器至少将消息route到一个队列中，
    #    否则就将消息return给发送者;
    template:
      mandatory: true
    #   RabbitMQ消息确认有2种：
    #     消息发送确认，
    #     消费接收确认。
    #       消息发送确认是确认生产者将消息发送到Exchange，
    #       Exchange分发消息至Queue的过程中，消息是否可靠投递。
    #       第一步是否到达Exchange，第二步确认是否到达Queue。

    #    实现ConfirmCallBack接口,消息发送到Exchange后触发回调。
    publisher-confirms: true
    #    实现ReturnCallBack接口，消息从Exchange发送到指定的Queue失败触发回调
    publisher-returns: true


dubbo:
  application:
    name: normal-trade-dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: >
      com.huiaong.normal.trade.impl.service,
      com.huiaong.normal.trade.impl.producer


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.normal.trade.(mq).model
