
server:
  port: 8080

dubbo:
  scan:
    basePackages: com.huiaong.normal.admin.order.controller
  application:
    name: normal-admin-dubbo-consumer
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
